In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('data/train.csv')

In [3]:
data[:1]

item_id  target_label  sold_price  diff_price  capital_area  status  size  \
0     7966           0.0        1164          -2             0       0     7   

   listing_at_spring  
0                  1

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 375 entries, 0 to 374
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   item_id            375 non-null    int64  
 1   target_label       375 non-null    float64
 2   sold_price         375 non-null    int64  
 3   diff_price         375 non-null    int64  
 4   capital_area       375 non-null    int64  
 5   status             375 non-null    int64  
 6   size               375 non-null    int64  
 7   listing_at_spring  375 non-null    int64  
dtypes: float64(1), int64(7)
memory usage: 23.6 KB


In [5]:
data.target_label.unique()

array([0., 1.])

In [6]:
from sklearn.linear_model import LogisticRegression

In [9]:
model = LogisticRegression()
model.fit(data.drop(['item_id','target_label'], axis = 1),data[['target_label']])

/opt/anaconda3/envs/mercari/lib/python3.7/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
/opt/anaconda3/envs/mercari/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [24]:
?model.fit

In [13]:
data.iloc[0]

item_id              7966.0
target_label            0.0
sold_price           1164.0
diff_price             -2.0
capital_area            0.0
status                  0.0
size                    7.0
listing_at_spring       1.0
Name: 0, dtype: float64

In [17]:
import numpy as np

In [28]:
data.drop(['item_id','target_label'],axis=1)[:1]

sold_price  diff_price  capital_area  status  size  listing_at_spring
0        1164          -2             0       0     7                  1

In [30]:
data[:1]

item_id  target_label  sold_price  diff_price  capital_area  status  size  \
0     7966           0.0        1164          -2             0       0     7   

   listing_at_spring  
0                  1

In [29]:
model.predict(data.drop(['item_id','target_label'],axis=1)[:1])

array([0.])

In [31]:
import pickle

In [32]:
filename = 'model.pkl'
pickle.dump(model, open(filename, 'wb'))

In [33]:
model = LogisticRegression()

In [35]:
model_path = 'model/model.pkl'

with open(model_path, 'rb') as f:
    model.clf = pickle.load(f)

In [36]:
model.predict(data.drop(['item_id','target_label'],axis=1)[:1])

NotFittedError: This LogisticRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [39]:
del model

In [40]:
model

NameError: name 'model' is not defined

In [43]:
model_path = 'model/model.pkl'

model = pickle.load(open(model_path, 'rb'))

In [44]:
model.predict(data.drop(['item_id','target_label'],axis=1)[:1])

array([0.])